FROM golang:1.23-alpine AS build

WORKDIR /src

COPY go.mod ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/pwned ./cmd/pwned

FROM gcr.io/distroless/static-debian12

WORKDIR /app
COPY --from=build /out/pwned /app/pwned

ENTRYPOINT ["/app/pwned"]
